### PR TITLE
Fix #6, special mode

### LINKED ISSUE #6: investigate special mode commands - error and intensity.
from datasheet 9.4 page 16, 

_The TLC591x provides two operation modes: Normal Mode and Special Mode. Normal mode is used for shifting
LED data into and out of the driver. Special Mode includes two functions: Error Detection and Current Gain
Control._

#### Error Detection

_In the Special Mode phase, the low-voltage-level signal on OE(ED2) can enable output channels and detect the
status of the output current to determine if the driving current level is sufficient. The detected Error Status is
loaded into the 8-bit shift register and shifted out via the pin SDO, synchronous to the CLK signal. The system
controller can read the error status and determine if the LEDs are properly lit._

This function needs to connect the SDO line and read back values. 
For me this has lower priority so will not be implemented yet.

#### Current Gain Control

_In the Special Mode phase, the TLC591x allows users to adjust the output current level by setting a runtime 
programmable Configuration Code. The code is sent into the TLC591x through SDI. The positive pulse of
LE(ED1) latches the code in the shift register into a built-in 8-bit configuration latch, instead of the output latch.
The code affects the voltage at the terminal R-EXT and controls the output-current regulator. The output current
can be finely adjusted by a gain ranging from 1/12 to 127/128 in 256 steps. Therefore, the current skew between
ICs can be compensated within less than 1%. This feature is suitable for white balancing in LED color display
panels._

This is the most important function (imho) of the Special mode, so that needs to be implemented first.

### PR DESCRIPTION
**Pull request by RobTillaart**

### CODE REVIEW

**Comment by Devilscave** [comment]
I'm not quite sure how to update the mode.
Can you give me some information?

**Comment by RobTillaart** [comment]
@Devilscave 
you need to call **tlc.setCurrentAdjustMode()** to get in to the special mode. 
Think I must rename that function ;)

Then you call **tlc.writeConfiguration(uint8_t config)**  config 0..255

To go back to normal mode call **tlc.setNormalMode();**

**Comment by Devilscave** [comment]
>  Ich glaube, ich muss diese Funktion umbenennen ;)

Wouldn't tlc.setMode(0), or (1) be possible?
Or simple tlc.SpezialMode() between tlc.NormalMode()
Or what did you have in mind?
You could also add a query to this:
tlc.getMode()

**Comment by RobTillaart** [comment]
That is indeed the direction of my thoughts

**Pull request merged**
